# Generated by Django 4.2.7 on 2026-09-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_dispatch_options_alter_fabric_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trim',
            options={},
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='fabric_code',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='trim_code',
        ),
    ]
