# Generated by Django 4.2.7 on 2026-09-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_fabric_options_alter_trim_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='purchase_order',
        ),
    ]
