# Generated by Django 4.2.7 on 2026-09-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_goodsreceipt_purchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='receipt_number',
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='accepted_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
