# Generated by Django 4.2.7 on 2026-09-14 13:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankaccount_banktransaction_costsheet_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_remove_goodsreceipt_receipt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_trims', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trim_receipts', to='accounts.supplier')),
            ],
            options={
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'ordering': ['-adjustment_date']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-movement_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='accepted_quantity',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='inspection_notes',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='inspector_name',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='quality_status',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='receipt_type',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='rejected_quantity',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptdetail',
            name='quantity_accepted',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptdetail',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptdetail',
            name='quantity_rejected',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptdetail',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptdetail',
            name='trim',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='adjustment_number',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='movement_number',
        ),
        migrations.AddField(
            model_name='goodsreceiptdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='direction',
            field=models.CharField(choices=[('increase', 'Increase Stock'), ('decrease', 'Decrease Stock')], default='decrease', max_length=10),
        ),
        migrations.AlterField(
            model_name='goodsreceiptdetail',
            name='fabric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='inventory.fabric'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsreceiptdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goodsreceiptdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='TrimReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='inventory.trim')),
                ('trim_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.trimreceipt')),
            ],
        ),
    ]
