# Generated by Django 4.2.7 on 2026-09-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_trimreceipt_alter_stockadjustment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedgoods',
            options={'ordering': ['size', 'color']},
        ),
        migrations.RemoveField(
            model_name='finishedgoods',
            name='style',
        ),
    ]
