# Generated by Django 4.2.7 on 2026-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_finishedgoods_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Goods Receipt'), ('production', 'Production / Stock In'), ('issue', 'Production Issue'), ('return', 'Return to Store'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Transfer Between Locations'), ('dispatch', 'Dispatch to Buyer')], max_length=20),
        ),
    ]
