# Generated by Django 4.2.7 on 2026-09-16 15:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankaccount_banktransaction_costsheet_payment_and_more'),
        ('inventory', '0008_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='fabric',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='accounts.buyer'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='accounts.purchaseorder'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='accounts.style'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to='accounts.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_type',
            field=models.CharField(choices=[('shell', 'Shell'), ('lining', 'Lining'), ('interlining', 'Interlining'), ('inner-lining', 'Inner-lining'), ('pocket', 'Pocket'), ('cotton', 'Cotton'), ('polyester', 'Polyester'), ('denim', 'Denim'), ('silk', 'Silk'), ('wool', 'Wool'), ('linen', 'Linen'), ('blend', 'Blend'), ('other', 'Other')], default='cotton', max_length=20),
        ),
        migrations.AlterField(
            model_name='fabricroll',
            name='lot_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('damage', 'Damage Write-off'), ('expired', 'Expired Stock'), ('qc_failure', 'QC Failure'), ('recount', 'Recount Adjustment'), ('return', 'Return to Supplier'), ('issue', 'Issued to Production'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockAdjustmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fabric_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_details', to='inventory.fabricroll')),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.stockadjustment')),
            ],
        ),
    ]
