# Generated by Django 4.2.7 on 2026-09-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankaccount_banktransaction_costsheet_payment_and_more'),
        ('inventory', '0009_remove_fabric_reorder_level_fabric_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='accounts.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
