# Generated by Django 4.2.7 on 2026-09-18 04:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_leave_leave_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_bankaccount_banktransaction_costsheet_payment_and_more'),
        ('inventory', '0011_dispatch_shipment_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('machine_name', models.CharField(max_length=200)),
                ('machine_type', models.CharField(choices=[('sewing_single_needle', 'Sewing - Single Needle Lockstitch'), ('sewing_overlock', 'Sewing - Overlock / Serger'), ('sewing_flatlock', 'Sewing - Flatlock / Interlock'), ('sewing_bartack', 'Sewing - Bartack'), ('sewing_buttonhole', 'Sewing - Buttonhole'), ('sewing_button_attach', 'Sewing - Button Attach'), ('sewing_kansai', 'Sewing - Kansai (Multi-needle)'), ('cutting_straight_knife', 'Cutting - Straight Knife'), ('cutting_band_knife', 'Cutting - Band Knife'), ('fusing_press', 'Fusing Press'), ('embroidery', 'Embroidery'), ('washing', 'Washing Machine'), ('dryer', 'Dryer'), ('boiler', 'Boiler'), ('generator', 'Generator'), ('compressor', 'Air Compressor'), ('iron_press', 'Iron / Steam Press'), ('needle_detector', 'Needle Detector'), ('other', 'Other')], default='other', max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('line_number', models.CharField(blank=True, help_text='e.g. Line-3', max_length=50)),
                ('location', models.CharField(blank=True, help_text='e.g. Floor 2, Line 3, Station 12', max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('under_maintenance', 'Under Maintenance'), ('broken_down', 'Broken Down'), ('sold', 'Sold'), ('scrapped', 'Scrapped'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_added', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='hr.department')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='accounts.supplier')),
            ],
            options={
                'ordering': ['machine_code'],
            },
        ),
        migrations.CreateModel(
            name='MachineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('breakdown', 'Breakdown Reported'), ('repair_started', 'Repair Started'), ('repair_completed', 'Repair Completed'), ('maintenance', 'Routine Maintenance'), ('relocated', 'Relocated'), ('sold', 'Sold'), ('scrapped', 'Scrapped'), ('other', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Repair cost or sale price, if applicable', max_digits=12, null=True)),
                ('counterparty', models.CharField(blank=True, help_text='Buyer, vendor or technician name', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_machine_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_events_logged', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.machine')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('needle', 'Needle'), ('motor', 'Motor'), ('belt', 'Belt'), ('bobbin', 'Bobbin'), ('presser_foot', 'Presser Foot'), ('bearing', 'Bearing'), ('gear', 'Gear'), ('electronic_board', 'Electronic Board / PCB'), ('blade', 'Blade / Knife'), ('other', 'Other')], default='other', max_length=30)),
                ('compatible_machine_type', models.CharField(blank=True, choices=[('sewing_single_needle', 'Sewing - Single Needle Lockstitch'), ('sewing_overlock', 'Sewing - Overlock / Serger'), ('sewing_flatlock', 'Sewing - Flatlock / Interlock'), ('sewing_bartack', 'Sewing - Bartack'), ('sewing_buttonhole', 'Sewing - Buttonhole'), ('sewing_button_attach', 'Sewing - Button Attach'), ('sewing_kansai', 'Sewing - Kansai (Multi-needle)'), ('cutting_straight_knife', 'Cutting - Straight Knife'), ('cutting_band_knife', 'Cutting - Band Knife'), ('fusing_press', 'Fusing Press'), ('embroidery', 'Embroidery'), ('washing', 'Washing Machine'), ('dryer', 'Dryer'), ('boiler', 'Boiler'), ('generator', 'Generator'), ('compressor', 'Air Compressor'), ('iron_press', 'Iron / Steam Press'), ('needle_detector', 'Needle Detector'), ('other', 'Other')], max_length=30)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('max_stock', models.IntegerField(default=99999)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='accounts.supplier')),
            ],
            options={
                'ordering': ['part_name'],
            },
        ),
        migrations.CreateModel(
            name='StationeryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('paper', 'Paper'), ('writing', 'Writing Materials'), ('printing', 'Printing / Toner'), ('filing', 'Filing & Organization'), ('cleaning', 'Cleaning Supplies'), ('other', 'Other')], default='other', max_length=30)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('max_stock', models.IntegerField(default=99999)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('damage', 'Damage Write-off'), ('expired_obsolete', 'Expired / Obsolete'), ('recount', 'Recount Adjustment'), ('other', 'Other')], max_length=20)),
                ('direction', models.CharField(choices=[('increase', 'Increase Stock'), ('decrease', 'Decrease Stock')], default='decrease', max_length=10)),
                ('adjustment_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supply_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supply_adjustments', to=settings.AUTH_USER_MODEL)),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='inventory.sparepart')),
                ('stationery_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='inventory.stationeryitem')),
            ],
            options={
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='StationeryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_at_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumption_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stationery_consumptions', to='hr.department')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationery_consumptions', to=settings.AUTH_USER_MODEL)),
                ('stationery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.stationeryitem')),
            ],
            options={
                'ordering': ['-consumption_date'],
            },
        ),
        migrations.CreateModel(
            name='SparePartConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_at_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumption_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_consumptions', to='hr.department')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_consumptions', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_consumptions', to='inventory.machine')),
                ('machine_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_consumptions', to='inventory.machineevent')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.sparepart')),
            ],
            options={
                'ordering': ['-consumption_date'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.sparepart'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stationery_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stationeryitem'),
        ),
    ]
