# Generated by Django 4.2.7 on 2026-09-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_project_rebuild'),
        ('inventory', '0012_machine_machineevent_sparepart_stationeryitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='finishedgoodsproduction',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='productionissue',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.project'),
        ),
    ]
