# Generated by Django 4.2.7 on 2026-09-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_dispatch_style_alter_fabric_style_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='style',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='fabric',
            old_name='style',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='finishedgoodsproduction',
            old_name='style',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='productionissue',
            old_name='style',
            new_name='project',
        ),
    ]
