# Generated by Django 4.2.7 on 2026-09-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_style_dispatch_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='buyer',
        ),
    ]
