# Generated by Django 4.2.7 on 2026-09-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_dispatch_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='purchase_order',
        ),
    ]
